# Time in seconds to wait for new messages in kafka before exiting
# Value of -1 means infinte wait
max_poll_timeout: 20

# Count of messages to be read from kafka before exiting
# Value of <= 0 means infinite wait
count: 0

# Count of messages written per file
# max_messages_per_file: 100000

# Specify the output file format in which data must be written.
# Possible values: JSON (for JSON format) and CSV (for csv format)
output_format: CSV

# Path to the avro schema file.
avro_schema: /home/osboxes/MyRepos/csv2kafka/cmd/kafka2csv/schema/hits.avsc

# Name of kafka topic to consume the messages from.
kafka_topic: hits_1

# Path to Kafka consumer.properties file.
kafka_properties: /home/osboxes/MyRepos/csv2kafka/cmd/kafka2csv/config/consumer.properties
