run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - errcheck
    - gci
    - gocritic
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - whitespace
  disable:
    - deadcode
    - goprintffuncname
    - gosimple
    - rowserrcheck
    - stylecheck
    - unparam
    - unused

linters-settings:

#deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck
