on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**.go'
  pull_request:
    branches:
      - master

name: run tests
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
